PATH=github.com/nvwa-io/nvwa-io/nvwa-server/clients/ansible

version:
	go test -count=1 -v ${PATH}  -run=Test_Version

exec-shell:
	go test -count=1 -v ${PATH}  -run=Test_ExecShell

copy-file:
	go test -count=1 -v ${PATH}  -run=Test_CopyFile

